name: ImmersivePortalsPaperized
version: 1.1.1
main: org.envel.immersiveportalspaperized.bukkit.ImmersivePortalsPaperized
description: "Plugin which allows nether portals to be seen through, and allows custom portal creation"
folia-supported: true
author: Envel
depend:
  - ProtocolLib
api-version: "1.21"
softdepend:
  - Multiverse-Core
  - My_Worlds
  - Vault
commands:
  immersiveportalspaperized:
    description: Main plugin command
    aliases:
      - bp
permissions:
  immersiveportalspaperized.createfromcoords:
    description: ' Allows you to use /bp createfromcoords'
    default: op
  immersiveportalspaperized.getname:
    description: ' Allows you to use /bp getportalname'
    default: op
  immersiveportalspaperized.link:
    description: ' Allows you to create portals with /bp link'
    default: op
  immersiveportalspaperized.linkexternal:
    description: ' Allows you to run /bp linkexternal to create cross-server portals.'
    default: op
  immersiveportalspaperized.remove:
    description: ' Allows you to use /bp remove and /bp removebyname'
    default: op
  immersiveportalspaperized.remove.others:
    description: ' Allows you to remove portals you do not own'
    default: op
  immersiveportalspaperized.reload:
    description: ' Allows you to use /bp reload'
    default: op
  immersiveportalspaperized.reconnect:
    description: ' Allows you to use /bp reconnect'
    default: op
  immersiveportalspaperized.select:
    description: ' Allows you to use /bp setOrigin, /bp setDestination and /bp menu'
    default: op
  immersiveportalspaperized.setname:
    description: ' Allows you to use /bp setPortalName, /bp setprice and /bp setpreset'
    default: op
  immersiveportalspaperized.setname.others:
    description: ' Allows you to rename portals you do not own'
    default: op
  immersiveportalspaperized.getallowNonPlayerTeleportation:
    description: ' Allows you to use /bp getallowNonPlayerTeleportation'
    default: op
  immersiveportalspaperized.setAllowNonPlayerTeleportation:
    description: ' Allows you to use /bp setAllowNonPlayerTeleportation'
    default: op
  immersiveportalspaperized.wand:
    description: ' Allows you to use /bp wand'
    default: op
  immersiveportalspaperized.user:
    description: ' Allows you to use portals'
    default: true
  immersiveportalspaperized.see:
    description: ' Allows you to see through portals'
    default: true
